### PR TITLE
Update recipe with new dependencies - Grayskull

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Updated dependencies using [Grayskull](https://github.com/marcelotrevisani/grayskull) :skull:

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
@conda-forge-admin , please rerender

**Comment by marcelotrevisani** [comment]
It is passing :tada: :tada: :tada: 

giphy

**Comment by marcelotrevisani** [comment]
Hi @knaaptime ,
Could you please take a look if the dependencies are ok?

**Review by sjsrey — APPROVED** [review]

**Comment by knaaptime** [comment]
looks good to me!

**Pull request merged**
